In [1]:
lst = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
my_vector = np.array(lst)

In [4]:
my_vector

array([1, 2, 3])

In [5]:
new_lst = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix = np.array(new_lst)

In [6]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_1 = np.arange(0,5)

In [8]:
arr_1

array([0, 1, 2, 3, 4])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(1)

array([0.51594093])

In [16]:
np.random.rand(3,3)

array([[0.62688954, 0.24258967, 0.86397563],
       [0.46213496, 0.53799335, 0.21556008],
       [0.53735178, 0.52885908, 0.62298751]])

In [17]:
np.random.randn(1) # Random Gaussian (Normal) Distribution

array([0.64189418])

In [19]:
np.random.randn(4)

array([ 0.33331199, -1.2575952 ,  0.31907124, -0.24300548])

In [20]:
np.random.randint(1, 7)

2

In [21]:
np.random.randint(1, 7, (2, 2))

array([[4, 2],
       [4, 4]])

In [22]:
arr = np.arange(25)

In [23]:
arr_2 = arr.reshape(5,5)

In [24]:
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr_2.shape

(5, 5)

In [26]:
arr.shape

(25,)

In [33]:
arr_3 = arr.reshape(-1, 5)

In [34]:
arr_3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.resize(5,5)

In [41]:
arr.max()

24

In [42]:
arr.argmax()

24

In [43]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [46]:
arr = np.arange(0.2, 1.3, 0.2)

In [47]:
arr

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [48]:
mat = np.random.randint(1, 7, (3, 3))

In [49]:
mat

array([[6, 1, 1],
       [5, 3, 5],
       [1, 1, 6]])

In [50]:
mat[1, 1] # mat[1][1] is valid too

3

In [51]:
mat[1:2, 1:] # mat[1:2][1:] is valid too

array([[3, 5]])

In [52]:
mat[1:2, 1:] = 8 # Broadcasting for arrays (Not for a list)

In [53]:
mat

array([[6, 1, 1],
       [5, 8, 8],
       [1, 1, 6]])

In [59]:
mat[0][0] = 2

In [60]:
mat

array([[2, 1, 1],
       [5, 8, 8],
       [1, 1, 6]])

In [61]:
mat[:, 2] = -1

In [63]:
mat[2][:] = 7

In [64]:
mat

array([[ 2,  1, -1],
       [ 5,  8, -1],
       [ 7,  7,  7]])

In [67]:
mat[:][1] = 9 # ?? Weird

In [69]:
mat[:, 1] = 10

In [70]:
mat

array([[ 2, 10, -1],
       [ 9, 10,  9],
       [ 7, 10,  7]])

In [71]:
arr = np.random.randint(1, 11, 10)

In [72]:
arr

array([ 8,  7,  9,  5,  6,  2,  1,  8,  8, 10])

In [75]:
arr.argmin()

6

In [76]:
arr_1 = arr[arr > 5]

In [77]:
arr_1

array([ 8,  7,  9,  6,  8,  8, 10])